const nav=document.getElementById('site-nav');const progress=document.querySelector('.progress span');const cursor=document.querySelector('.cursor');const menu=document.querySelector('.mobile-menu');const toggle=document.querySelector('.menu-toggle');
function onScroll(){const max=document.documentElement.scrollHeight-window.innerHeight;if(progress)progress.style.width=`${max>0?(window.scrollY/max)*100:0}%`;}window.addEventListener('scroll',onScroll,{passive:true});onScroll();
if(toggle&&menu){toggle.addEventListener('click',()=>{const open=menu.classList.toggle('open');toggle.setAttribute('aria-expanded',String(open));menu.setAttribute('aria-hidden',String(!open));document.body.style.overflow=open?'hidden':'';});menu.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{menu.classList.remove('open');toggle.setAttribute('aria-expanded','false');menu.setAttribute('aria-hidden','true');document.body.style.overflow='';}));document.addEventListener('keydown',e=>{if(e.key==='Escape'&&menu.classList.contains('open')){menu.classList.remove('open');toggle.setAttribute('aria-expanded','false');menu.setAttribute('aria-hidden','true');document.body.style.overflow='';toggle.focus();}});}
const revealObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');revealObserver.unobserve(entry.target);}}),{threshold:.08,rootMargin:'0px 0px -50px'});document.querySelectorAll('.reveal').forEach((el,i)=>{el.style.transitionDelay=`${Math.min(i*55,350)}ms`;revealObserver.observe(el);});
function count(el){const target=Number(el.dataset.count);if(!Number.isFinite(target))return;const suffix=el.dataset.suffix||'';const start=performance.now();function frame(now){const p=Math.min((now-start)/1100,1),eased=1-Math.pow(1-p,3);el.textContent=`${Math.round(target*eased)}${suffix}`;if(p<1)requestAnimationFrame(frame);}requestAnimationFrame(frame);}const counterObserver=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){count(e.target);counterObserver.unobserve(e.target);}}),{threshold:.5});document.querySelectorAll('[data-count]').forEach(el=>counterObserver.observe(el));
const filters=document.querySelectorAll('.filter'),projects=document.querySelectorAll('.project');filters.forEach(filter=>filter.addEventListener('click',()=>{filters.forEach(f=>f.classList.remove('active'));filter.classList.add('active');const value=filter.dataset.filter;projects.forEach(card=>{card.style.display=value==='all'||card.dataset.category===value?'':'none';});}));
if(cursor&&window.matchMedia('(pointer:fine)').matches){let mx=0,my=0,cx=0,cy=0;window.addEventListener('pointermove',e=>{mx=e.clientX;my=e.clientY;});function cursorFrame(){cx+=(mx-cx)*.18;cy+=(my-cy)*.18;cursor.style.left=`${cx}px`;cursor.style.top=`${cy}px`;requestAnimationFrame(cursorFrame);}requestAnimationFrame(cursorFrame);document.querySelectorAll('a,button,.project,.service,.metric').forEach(el=>{el.addEventListener('mouseenter',()=>{cursor.style.width='34px';cursor.style.height='34px';});el.addEventListener('mouseleave',()=>{cursor.style.width='18px';cursor.style.height='18px';});});document.querySelectorAll('.magnetic').forEach(el=>el.addEventListener('pointermove',e=>{const r=el.getBoundingClientRect();el.style.transform=`translate(${(e.clientX-(r.left+r.width/2))*.12}px,${(e.clientY-(r.top+r.height/2))*.12}px)`;}));document.querySelectorAll('.magnetic').forEach(el=>el.addEventListener('pointerleave',()=>el.style.transform=''));}
const portrait=document.querySelector('[data-parallax]');if(portrait&&window.matchMedia('(pointer:fine)').matches){window.addEventListener('pointermove',e=>{const x=(e.clientX/window.innerWidth-.5)*10,y=(e.clientY/window.innerHeight-.5)*10;portrait.style.transform=`translate(${x}px,${y}px)`;},{passive:true});}
document.querySelectorAll('a[href^="#"]').forEach(a=>a.addEventListener('click',e=>{const id=a.getAttribute('href');if(!id||id==='#')return;const target=document.querySelector(id);if(!target)return;e.preventDefault();const offset=nav?.offsetHeight||74;window.scrollTo({top:target.getBoundingClientRect().top+window.scrollY-offset,behavior:'smooth'});}));
const form=document.getElementById('contact-form');if(form){form.addEventListener('submit',e=>{e.preventDefault();const data=new FormData(form),name=String(data.get('name')||'').trim(),email=String(data.get('email')||'').trim(),message=String(data.get('message')||'').trim();if(!name||!email||!message){form.reportValidity();return;}const subject=encodeURIComponent(`Portfolio inquiry from ${name}`),body=encodeURIComponent(`Name: ${name}\nEmail: ${email}\n\nGrowth challenge:\n${message}`),button=form.querySelector('button');if(button){button.textContent='Opening email…';button.disabled=true;}window.location.href=`mailto:ammardigital04@gmail.com?subject=${subject}&body=${body}`;setTimeout(()=>{if(button){button.textContent='Send inquiry ↗';button.disabled=false;}},3000);});}

const caseData={
"real-estate":{title:"Real Estate Lead Generation",subtitle:"Meta Ads · Lead Generation · 90-day illustrative campaign",challenge:"Generate a consistent flow of qualified real-estate leads while keeping acquisition efficient.",objective:"Build a repeatable lead-generation funnel with stronger audience and creative signals.",strategy:"Segment cold audiences, test intent-led messaging, build a lead funnel and retarget engaged users.",execution:"Campaign setup, audience research, creative testing, budget allocation, retargeting and weekly optimization.",results:[["1,850+","Illustrative leads"],["₹135","Illustrative CPL"],["3.2×","Illustrative return"],["+42%","Illustrative conversion improvement"]]},
"saas":{title:"SaaS Google Ads Growth",subtitle:"Google Ads · Search · Conversion Optimization",challenge:"Capture high-intent SaaS demand without wasting spend on low-intent queries.",objective:"Improve search efficiency and conversion quality.",strategy:"Map keywords by intent, build tightly themed campaigns, improve ad-to-landing-page alignment and track conversions.",execution:"Keyword research, search campaign structure, ad testing, negative keywords, tracking and landing-page recommendations.",results:[["₹1.8L","Illustrative spend"],["420+","Illustrative conversions"],["3.2×","Illustrative ROAS"],["+38%","Illustrative CVR improvement"]]},
"ecommerce":{title:"E-commerce Performance Campaign",subtitle:"Meta Ads · E-commerce · Retargeting",challenge:"Create a scalable acquisition loop across new and returning shoppers.",objective:"Increase purchase efficiency through full-funnel campaign design.",strategy:"Separate prospecting and retargeting, test product-led creatives and shift budget toward stronger audience-creative combinations.",execution:"Campaign architecture, creative testing, audience segmentation, retargeting and performance reporting.",results:[["₹3L","Illustrative spend"],["4.1×","Illustrative ROAS"],["+68%","Illustrative revenue"],["−29%","Illustrative CPA"]]},
"local-seo":{title:"Local Business SEO Growth",subtitle:"SEO · Local Search · Organic Growth",challenge:"Improve local visibility for commercial-intent searches.",objective:"Grow qualified organic traffic and local leads.",strategy:"Fix technical issues, map keywords to intent, improve local signals and build useful supporting content.",execution:"Keyword research, on-page optimization, technical recommendations, content mapping and Search Console monitoring.",results:[["+145%","Illustrative traffic"],["+82%","Illustrative leads"],["Top 5","Target keywords"],["+61%","Illustrative visibility"]]},
"b2b":{title:"B2B Lead Generation",subtitle:"Google Ads · B2B · Lead Generation",challenge:"Reach high-intent business buyers while filtering out low-quality demand.",objective:"Build a more qualified and measurable lead pipeline.",strategy:"Use intent-based search structure, qualification-focused messaging and conversion tracking.",execution:"Keyword strategy, campaign setup, ad copy testing, conversion tracking and budget optimization.",results:[["680+","Illustrative leads"],["₹324","Illustrative CPL"],["+47%","Illustrative lead quality"],["2.6×","Illustrative return"]]},
"social-growth":{title:"Social Media Growth",subtitle:"Social Media · Content · Paid Distribution",challenge:"Build consistent reach and engagement without relying on one content format.",objective:"Create a repeatable content and distribution system.",strategy:"Define content pillars, test hooks and formats, amplify winners and learn from audience response.",execution:"Content planning, creative direction, publishing system, paid distribution and performance analysis.",results:[["+178%","Illustrative reach"],["+94%","Illustrative engagement"],["+62%","Illustrative followers"],["+41%","Illustrative saves"]]},
"startup":{title:"Startup Full-Funnel Growth",subtitle:"Growth Marketing · Meta Ads · Google Ads",challenge:"Connect acquisition activity to conversion rather than optimizing channels in isolation.",objective:"Build a measurable growth loop from traffic to conversion.",strategy:"Combine paid acquisition, landing-page optimization, retargeting and structured experimentation.",execution:"Funnel mapping, campaign setup, audience strategy, CRO recommendations, retargeting and reporting.",results:[["2.9×","Illustrative ROAS"],["+73%","Illustrative CVR"],["−31%","Illustrative CPA"],["+55%","Illustrative qualified demand"]]},
"organic":{title:"Organic Search Growth",subtitle:"SEO · Content Strategy · Technical SEO",challenge:"Increase organic discovery for high-intent topics.",objective:"Grow non-paid traffic and convert more search demand.",strategy:"Prioritize technical health, keyword clusters, content gaps and intent-led optimization.",execution:"Technical review, keyword mapping, on-page recommendations, content planning and GSC monitoring.",results:[["+210%","Illustrative traffic"],["+126%","Illustrative ranking keywords"],["+74%","Illustrative leads"],["+58%","Illustrative clicks"]]} };
const modal=document.getElementById("case-modal");
function openCase(key){const d=caseData[key];if(!d||!modal)return;document.getElementById("case-modal-title").textContent=d.title;document.getElementById("case-modal-subtitle").textContent=d.subtitle;document.getElementById("case-challenge").textContent=d.challenge;document.getElementById("case-objective").textContent=d.objective;document.getElementById("case-strategy").textContent=d.strategy;document.getElementById("case-execution").textContent=d.execution;document.getElementById("case-results").innerHTML=d.results.map(r=>`<div><strong>${r[0]}</strong><small>${r[1]}</small></div>`).join("");modal.classList.add("open");modal.setAttribute("aria-hidden","false");document.body.classList.add("modal-open");}
function closeCase(){if(!modal)return;modal.classList.remove("open");modal.setAttribute("aria-hidden","true");document.body.classList.remove("modal-open");}
document.querySelectorAll("[data-case-open]").forEach(b=>b.addEventListener("click",()=>openCase(b.dataset.caseOpen)));document.querySelectorAll("[data-case-close]").forEach(b=>b.addEventListener("click",closeCase));document.addEventListener("keydown",e=>{if(e.key==="Escape")closeCase();});
