const nav=document.getElementById('site-nav');const progress=document.querySelector('.progress span');const cursor=document.querySelector('.cursor');const menu=document.querySelector('.mobile-menu');const toggle=document.querySelector('.menu-toggle');
function onScroll(){const max=document.documentElement.scrollHeight-window.innerHeight;if(progress)progress.style.width=`${max>0?(window.scrollY/max)*100:0}%`;}window.addEventListener('scroll',onScroll,{passive:true});onScroll();
if(toggle&&menu){toggle.addEventListener('click',()=>{const open=menu.classList.toggle('open');toggle.setAttribute('aria-expanded',String(open));menu.setAttribute('aria-hidden',String(!open));document.body.style.overflow=open?'hidden':'';});menu.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{menu.classList.remove('open');toggle.setAttribute('aria-expanded','false');menu.setAttribute('aria-hidden','true');document.body.style.overflow='';}));document.addEventListener('keydown',e=>{if(e.key==='Escape'&&menu.classList.contains('open')){menu.classList.remove('open');toggle.setAttribute('aria-expanded','false');menu.setAttribute('aria-hidden','true');document.body.style.overflow='';toggle.focus();}});}
const revealObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');revealObserver.unobserve(entry.target);}}),{threshold:.08,rootMargin:'0px 0px -50px'});document.querySelectorAll('.reveal').forEach((el,i)=>{el.style.transitionDelay=`${Math.min(i*55,350)}ms`;revealObserver.observe(el);});
function count(el){const target=Number(el.dataset.count);if(!Number.isFinite(target))return;const suffix=el.dataset.suffix||'';const start=performance.now();function frame(now){const p=Math.min((now-start)/1100,1),eased=1-Math.pow(1-p,3);el.textContent=`${Math.round(target*eased)}${suffix}`;if(p<1)requestAnimationFrame(frame);}requestAnimationFrame(frame);}const counterObserver=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){count(e.target);counterObserver.unobserve(e.target);}}),{threshold:.5});document.querySelectorAll('[data-count]').forEach(el=>counterObserver.observe(el));
const filters=document.querySelectorAll('.filter'),projects=document.querySelectorAll('.project');filters.forEach(filter=>filter.addEventListener('click',()=>{filters.forEach(f=>f.classList.remove('active'));filter.classList.add('active');const value=filter.dataset.filter;projects.forEach(card=>{card.style.display=value==='all'||card.dataset.category===value?'':'none';});}));
if(cursor&&window.matchMedia('(pointer:fine)').matches){let mx=0,my=0,cx=0,cy=0;window.addEventListener('pointermove',e=>{mx=e.clientX;my=e.clientY;});function cursorFrame(){cx+=(mx-cx)*.18;cy+=(my-cy)*.18;cursor.style.left=`${cx}px`;cursor.style.top=`${cy}px`;requestAnimationFrame(cursorFrame);}requestAnimationFrame(cursorFrame);document.querySelectorAll('a,button,.project,.service,.metric').forEach(el=>{el.addEventListener('mouseenter',()=>{cursor.style.width='34px';cursor.style.height='34px';});el.addEventListener('mouseleave',()=>{cursor.style.width='18px';cursor.style.height='18px';});});document.querySelectorAll('.magnetic').forEach(el=>el.addEventListener('pointermove',e=>{const r=el.getBoundingClientRect();el.style.transform=`translate(${(e.clientX-(r.left+r.width/2))*.12}px,${(e.clientY-(r.top+r.height/2))*.12}px)`;}));document.querySelectorAll('.magnetic').forEach(el=>el.addEventListener('pointerleave',()=>el.style.transform=''));}
const portrait=document.querySelector('[data-parallax]');if(portrait&&window.matchMedia('(pointer:fine)').matches){window.addEventListener('pointermove',e=>{const x=(e.clientX/window.innerWidth-.5)*10,y=(e.clientY/window.innerHeight-.5)*10;portrait.style.transform=`translate(${x}px,${y}px)`;},{passive:true});}
document.querySelectorAll('a[href^="#"]').forEach(a=>a.addEventListener('click',e=>{const id=a.getAttribute('href');if(!id||id==='#')return;const target=document.querySelector(id);if(!target)return;e.preventDefault();const offset=nav?.offsetHeight||74;window.scrollTo({top:target.getBoundingClientRect().top+window.scrollY-offset,behavior:'smooth'});}));
const form=document.getElementById('contact-form');if(form){form.addEventListener('submit',e=>{e.preventDefault();const data=new FormData(form),name=String(data.get('name')||'').trim(),email=String(data.get('email')||'').trim(),message=String(data.get('message')||'').trim();if(!name||!email||!message){form.reportValidity();return;}const subject=encodeURIComponent(`Portfolio inquiry from ${name}`),body=encodeURIComponent(`Name: ${name}\nEmail: ${email}\n\nGrowth challenge:\n${message}`),button=form.querySelector('button');if(button){button.textContent='Opening email…';button.disabled=true;}window.location.href=`mailto:ammardigital04@gmail.com?subject=${subject}&body=${body}`;setTimeout(()=>{if(button){button.textContent='Send inquiry ↗';button.disabled=false;}},3000);});}

const caseData={
"mobglob":{title:"Mobglob",subtitle:"Product Brand · Mobile Accessories · Featured Project",challenge:"Build a clear digital identity for a mobile accessories brand.",objective:"Create a product-first presence that supports discovery and growth.",strategy:"Position the brand around distinctive products, creative direction and performance-led acquisition.",execution:"Brand positioning, content direction, digital presence and growth planning.",results:[["Brand","Mobile accessories"],["Type","Product"],["Focus","Growth"],["Scope","Digital"]]},
"cashly":{title:"Cashly",subtitle:"Digital Product · Featured Project",challenge:"Create a modern digital product presence that communicates value clearly.",objective:"Build a clear product journey with strong positioning.",strategy:"Combine product storytelling, audience messaging and a streamlined digital experience.",execution:"Product positioning, content structure and conversion journey planning.",results:[["Product","Digital"],["UX","Growth focused"],["Journey","Conversion"],["Brand","Modern"]]},
"pelquant":{title:"Pelquant",subtitle:"AI Software · Digital Marketing · Featured Project",challenge:"Establish a strong digital presence for an AI software company.",objective:"Build brand visibility and a performance-oriented marketing foundation.",strategy:"Combine brand positioning, social content and performance marketing.",execution:"Digital marketing strategy, social presence, content direction and campaign planning.",results:[["Industry","AI software"],["Scope","360° digital"],["Focus","Performance"],["Brand","Growth"]]},
"view360":{title:"View 360",subtitle:"Real Estate · Featured Project",challenge:"Make property discovery more engaging for potential customers.",objective:"Create a digital experience that improves property visibility.",strategy:"Use visual-first property presentation and conversion-focused journeys.",execution:"Real estate positioning, property content and lead-generation planning.",results:[["Industry","Real Estate"],["Experience","360°"],["Focus","Discovery"],["Journey","Lead focused"]]},
"nexon":{title:"Nexon",subtitle:"Social Media Platform · Featured Project",challenge:"Create a scalable social platform concept focused on audience engagement.",objective:"Build a platform identity centered on community and participation.",strategy:"Use clear positioning, engaging content loops and audience growth.",execution:"Platform positioning, social content direction and growth strategy.",results:[["Platform","Social"],["Focus","Community"],["Growth","Audience"],["Experience","Engagement"]]},
"swiss":{title:"Swiss Hospitality",subtitle:"Holiday Tours Management · Featured Project",challenge:"Create a polished digital experience for holiday tours.",objective:"Improve destination discovery, enquiries and the customer journey.",strategy:"Combine destination storytelling, service clarity and enquiry-focused experiences.",execution:"Hospitality positioning, tour content and digital marketing direction.",results:[["Industry","Hospitality"],["Service","Holiday tours"],["Focus","Enquiries"],["Journey","Travel"]]}
};
const modal=document.getElementById("case-modal");
function openCase(key){const d=caseData[key];if(!d||!modal)return;document.getElementById("case-modal-title").textContent=d.title;document.getElementById("case-modal-subtitle").textContent=d.subtitle;document.getElementById("case-challenge").textContent=d.challenge;document.getElementById("case-objective").textContent=d.objective;document.getElementById("case-strategy").textContent=d.strategy;document.getElementById("case-execution").textContent=d.execution;document.getElementById("case-results").innerHTML=d.results.map(r=>`<div><strong>${r[0]}</strong><small>${r[1]}</small></div>`).join("");modal.classList.add("open");modal.setAttribute("aria-hidden","false");document.body.classList.add("modal-open");}
function closeCase(){if(!modal)return;modal.classList.remove("open");modal.setAttribute("aria-hidden","true");document.body.classList.remove("modal-open");}
document.querySelectorAll("[data-case-open]").forEach(b=>b.addEventListener("click",()=>openCase(b.dataset.caseOpen)));document.querySelectorAll("[data-case-close]").forEach(b=>b.addEventListener("click",closeCase));document.addEventListener("keydown",e=>{if(e.key==="Escape")closeCase();});
