const nav=document.getElementById('site-nav');const progress=document.querySelector('.progress span');const cursor=document.querySelector('.cursor');const menu=document.querySelector('.mobile-menu');const toggle=document.querySelector('.menu-toggle');
function onScroll(){const max=document.documentElement.scrollHeight-window.innerHeight;if(progress)progress.style.width=`${max>0?(window.scrollY/max)*100:0}%`;}window.addEventListener('scroll',onScroll,{passive:true});onScroll();
if(toggle&&menu){toggle.addEventListener('click',()=>{const open=menu.classList.toggle('open');toggle.setAttribute('aria-expanded',String(open));menu.setAttribute('aria-hidden',String(!open));document.body.style.overflow=open?'hidden':'';});menu.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{menu.classList.remove('open');toggle.setAttribute('aria-expanded','false');menu.setAttribute('aria-hidden','true');document.body.style.overflow='';}));document.addEventListener('keydown',e=>{if(e.key==='Escape'&&menu.classList.contains('open')){menu.classList.remove('open');toggle.setAttribute('aria-expanded','false');menu.setAttribute('aria-hidden','true');document.body.style.overflow='';toggle.focus();}});}
const revealObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');revealObserver.unobserve(entry.target);}}),{threshold:.08,rootMargin:'0px 0px -50px'});document.querySelectorAll('.reveal').forEach((el,i)=>{el.style.transitionDelay=`${Math.min(i*55,350)}ms`;revealObserver.observe(el);});
function count(el){const target=Number(el.dataset.count);if(!Number.isFinite(target))return;const suffix=el.dataset.suffix||'';const start=performance.now();function frame(now){const p=Math.min((now-start)/1100,1),eased=1-Math.pow(1-p,3);el.textContent=`${Math.round(target*eased)}${suffix}`;if(p<1)requestAnimationFrame(frame);}requestAnimationFrame(frame);}const counterObserver=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){count(e.target);counterObserver.unobserve(e.target);}}),{threshold:.5});document.querySelectorAll('[data-count]').forEach(el=>counterObserver.observe(el));
const filters=document.querySelectorAll('.filter'),projects=document.querySelectorAll('.project');filters.forEach(filter=>filter.addEventListener('click',()=>{filters.forEach(f=>f.classList.remove('active'));filter.classList.add('active');const value=filter.dataset.filter;projects.forEach(card=>{card.style.display=value==='all'||card.dataset.category===value?'':'none';});}));
if(cursor&&window.matchMedia('(pointer:fine)').matches){let mx=0,my=0,cx=0,cy=0;window.addEventListener('pointermove',e=>{mx=e.clientX;my=e.clientY;});function cursorFrame(){cx+=(mx-cx)*.18;cy+=(my-cy)*.18;cursor.style.left=`${cx}px`;cursor.style.top=`${cy}px`;requestAnimationFrame(cursorFrame);}requestAnimationFrame(cursorFrame);document.querySelectorAll('a,button,.project,.service,.metric').forEach(el=>{el.addEventListener('mouseenter',()=>{cursor.style.width='34px';cursor.style.height='34px';});el.addEventListener('mouseleave',()=>{cursor.style.width='18px';cursor.style.height='18px';});});document.querySelectorAll('.magnetic').forEach(el=>el.addEventListener('pointermove',e=>{const r=el.getBoundingClientRect();el.style.transform=`translate(${(e.clientX-(r.left+r.width/2))*.12}px,${(e.clientY-(r.top+r.height/2))*.12}px)`;}));document.querySelectorAll('.magnetic').forEach(el=>el.addEventListener('pointerleave',()=>el.style.transform=''));}
const portrait=document.querySelector('[data-parallax]');if(portrait&&window.matchMedia('(pointer:fine)').matches){window.addEventListener('pointermove',e=>{const x=(e.clientX/window.innerWidth-.5)*10,y=(e.clientY/window.innerHeight-.5)*10;portrait.style.transform=`translate(${x}px,${y}px)`;},{passive:true});}
document.querySelectorAll('a[href^="#"]').forEach(a=>a.addEventListener('click',e=>{const id=a.getAttribute('href');if(!id||id==='#')return;const target=document.querySelector(id);if(!target)return;e.preventDefault();const offset=nav?.offsetHeight||74;window.scrollTo({top:target.getBoundingClientRect().top+window.scrollY-offset,behavior:'smooth'});}));
const form=document.getElementById('contact-form');if(form){form.addEventListener('submit',e=>{e.preventDefault();const data=new FormData(form),name=String(data.get('name')||'').trim(),email=String(data.get('email')||'').trim(),message=String(data.get('message')||'').trim();if(!name||!email||!message){form.reportValidity();return;}const subject=encodeURIComponent(`Portfolio inquiry from ${name}`),body=encodeURIComponent(`Name: ${name}\nEmail: ${email}\n\nGrowth challenge:\n${message}`),button=form.querySelector('button');if(button){button.textContent='Opening email…';button.disabled=true;}window.location.href=`mailto:ammardigital04@gmail.com?subject=${subject}&body=${body}`;setTimeout(()=>{if(button){button.textContent='Send inquiry ↗';button.disabled=false;}},3000);});}
